name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: pnpm-setup
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile

    - name: Generate Fonts
      run: pnpm run prepare-fonts

    - name: Build project
      run: pnpm run build

    - name: Archive production artifact
      run: tar -czvf release.tar.gz -C dist .

    - name: Determine Release Type
      id: determine-release
      run: |
        if [[ "${{ github.event.head_commit.message }}" == *"[beta-release]"* ]]; then
          echo "release_type=beta" >> $GITHUB_ENV
        else
          echo "release_type=ci" >> $GITHUB_ENV
        fi

    - name: Create Release
      env:
        tag_name: '${{ env.release_type }}-${{ github.run_number }}'
        release_name: '${{ env.release_type | upper }} Release ${{ github.run_number }}'
      run: |
        gh release create "$tag_name" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} ${tag_name}" \
          --generate-notes \
          $([[ "${{ env.release_type }}" == "beta" ]] && echo "--prerelease") \
          ./release.tar.gz
