name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: pnpm-setup
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile

    - name: Generate Fonts
      run: pnpm run prepare-fonts

    - name: Build project
      run: pnpm run build

    - name: Archive production artifact
      run: tar -czvf release.tar.gz -C dist .

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

    - name: Determine Release Type
      id: determine-release
      run: |
        if [[ "${{ github.event.head_commit.message }}" =~ \[release/v([0-9]+\.[0-9]+\.[0-9]+)\] ]]; then
          echo "release_type=release" >> $GITHUB_ENV
          echo "tag_name=v${BASH_REMATCH[1]}" >> $GITHUB_ENV
        else
          echo "release_type=ci" >> $GITHUB_ENV
          echo "tag_name=ci-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
        fi

    - name: Create Release
      env:
        # GH_TOKEN: ${{ secrets.GH_TOKEN }}
        tag_name: ${{ env.tag_name }}
      run: |
        gh release create "$tag_name" \
          --title="${GITHUB_REPOSITORY#*/} $tag_name" \
          --generate-notes \
          $([[ "$RELEASE_TYPE" == "ci" ]] && echo "--prerelease") \
          ./release.tar.gz
